name: Backend integration tests

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  run:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: Use Node.js 12.x
      uses: actions/setup-node@v1
      with:
        node-version: 12.x

    - name: Build the backend server
      run: |
        cd backend
        docker-compose build

    - name: Start MySQL and the backend server
      run: |
        cd backend
        docker-compose up -d

    - name: Wait for backend server to be ready
      run: |
        is_backend_running() {
            running=$(docker inspect backend_backend_1 | grep 'Running' | sed -E 's/.*(true|false).*/\1/')
            test $running = true
        }

        is_backend_ready() {
            latest_line=$(docker logs --tail 1 backend_backend_1)
            test "$latest_line" = 'Listening on port 4000'
        }

        die() {
            docker ps -a
            echo
            docker logs backend_backend_1
            exit 1
        }

        tries=60

        while true; do
            sleep 1

            if ! is_backend_running; then
                echo 'Error: Backend has quit'
                echo
                die
            fi

            if is_backend_ready; then
                exit 0
            fi

            tries=$((tries - 1))

            if [ $tries = 0 ]; then
                echo 'Error: Timeout after 60 seconds'
                echo
                die
            fi
        done

    - name: Run tests
      run: |
        cd backend
        yarn test
