name: Backend integration tests

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  run:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: Build the docker-compose stack
      run: |
        cd backend
        docker-compose build

    - name: Run the backend server
      run: |
        cd backend
        docker-compose up -d

    - name: Sleep 5 seconds
      run: sleep 5

    - name: Check the backend server status
      run: |
        docker ps -a
        echo

        docker logs -t backend_backend_1
        echo

        running=$(docker inspect backend_backend_1 | grep 'Running' | sed -E 's/.*(true|false).*/\1/')
        if [ "$running" = 'false' ]; then
            echo NOT RUNNING, ERROR
            exit 1
        else
            echo RUNNING, OK
        fi

    - name: Run tests
      run: sh backend/test.sh
